
package com.example.antikseruven;

public class Sorucevap {
    public static String soru[]={
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?",
            "Ahırdaki ineklerin ayaklarının toplamı 84’tür. Bu ahırda kaç inek vardır?",
            "Kümesteki tavukların ayakları toplamı 96’dır. Bu kümeste kaç tavuk vardır?",
            "Meryem Hanım yaptığı 68 kurabiyeyi altışarlı paketledi. Kalan kurabiyeyi de oğluna verdi. Buna göre oğlu kaç kurabiye yemiştir?",
            "Bekir 96 sayfalık hikâye kitabını eşit sayfalar okuyarak 6 günde bitiriyor. Buna göre Bekir bir günde kaç sayfa okumuştur?",
            "5 tanesine 30 TL ödediğimiz kalemin düzinesine kaç TL öderiz?"
    };
    public static String secenek[][]={
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"},
            {"20","21","22","23"},
            {"45","46","47","48"},
            {"1","2","3","4"},
            {"6","12","16","22"},
            {"45","72","60","50"}
    };
    public static String dogruCevap[]={
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
            "21",
            "48",
            "2",
            "16",
            "72",
    };
}
